version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: dev.env
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    env_file: dev.env
    restart: always
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
